/* =====================================================================
   ORION CAPITAL STELLAR OS — VERSION DÉMO (juillet 2026)
   ⚠ DONNÉES 100 % FICTIVES — aucune donnée réelle.
   Sociétés, actifs, locataires, montants et adresses inventés.
   Même schéma technique que 00-data.js (jamais chargé ici).
   ===================================================================== */
const YEAR_NOW = 2026;

const DEFAULT_DATA = {
  voxelEdits:{},
  meta:{version:"stellar-2.0-demo", build:"3.89-DEMO", updated:"2026-07-07", owner:"Version de démonstration — données fictives",
    brand:"Orion Capital", brandShort:"OC", brandDisplay:"ORION CAPITAL — DÉMO", city:"Région démo, France", cityShort:"DÉMO",
    bootNote:"mode démonstration — données 100 % fictives"},
  holding:{ cash:45000, ccConsolidated:220000, monthlyCharges:2900,
    kicker:"Holding de démonstration · données fictives",
    sub:"SAS fictive · 1 place de la Constellation · Démo",
    chargesNote:"/mois (paramètre de démonstration)",
    personal:{ sub:"NAV + éléments perso fictifs",
      items:[{lbl:"CC perso Nova (fictif)", v:12500, f:"eur"},{lbl:"part fonds Céphée (fictif)", v:145000, f:"k"}] },
    note:"Charges de structure fictives : 2 900€/mois. Tous les montants de cette démo sont inventés." },
  ui:{
    risk1:{title:"EP LYRA", sub:"Bail ferme → mi-2027 (scénario fictif). Coussin de trésorerie ~18 mois. Décision démo : relocation / arbitrage / portage."},
    doctrine:"Doctrine de démonstration : zéro dividende systématique — accumulation en trésorerie interne et désendettement. Extraction privilégiée par remboursement de comptes courants. Régime mère-fille ~1,25%. Tous les chiffres sont fictifs.",
    divNote:"Doctrine démo : privilégier le CC quand il existe. Extraction directe ≈ 45,3% vs ~21,9% via holding.",
    buyNote:"Modèle démo « honoraires recyclés » applicable pour neutraliser l'apport (illustration fictive).",
    presets:[
      {call:"presetCC('altair',15000)", color:"#6FE3FF", nm:"Altair — Scénario B", sub:"Remboursement partiel des CC (fictif). OC +15 000€. Trésorerie résiduelle confortable. Illustration."},
      {call:"presetCC('nova',120000)", color:"#5CC8FF", nm:"Nova — Remontée fictive", sub:"Liquidation d'une participation fictive fin 2026 : part OC ~120k€ + CC 9 500€."},
      {call:"presetSale('lyra')", color:"#FF6B5A", nm:"Lyra — Arbitrage", sub:"Cession à valeur vénale (fictive) si non-relocation avant mi-2027."},
      {call:"presetBuy()", color:"#FFC861", nm:"Acquisition type Vega", sub:"2M€, LTV 85%, 3,4%, rendement 7,5%, QP 25% — scénario de démonstration."}
    ],
    scDefaults:{cc:15000, div:80000, refi:400000, rate:3.4, dur:15, sale:1850000, tax:110000, buy:2000000, ltv:85, yld:7.5, stk:25}
  },
  people:[{n:"ALEX RIVIÈRE",r:"Président (personnage fictif)",col:"#FFD98A",rad:58,sp:.16,el:.22,ph:0.4,ring:true},
   {n:"CAMILLE FONTAINE",r:"Direction financière (fictif)",col:"#7FD0FF",rad:74,sp:-.13,el:-.16,ph:2.7,ring:false}],
  ai:{
    docSys:"Tu es le module Document AI de la démo Orion Capital Stellar OS (données 100 % fictives).",
    neuralTitle:"Orion Neural Ledger — copilote de démonstration",
    neuralWelcome:"Copilote de démonstration en ligne. Toutes les données de cette instance sont fictives : sociétés, actifs, locataires et montants inventés à des fins d'illustration.",
    neuralSys:"Tu es ORION NEURAL LEDGER, copilote patrimonial de DÉMONSTRATION intégré au Stellar OS d'Orion Capital (société fictive). Toutes les données sont fictives. Réponds en français, chiffré, structuré, concis. Tu n'es ni avocat ni CIF : analyses d'aide à la décision uniquement, sur données de démonstration.\nDOCTRINE DÉMO : zéro dividende systématique ; extraction via remboursements de CC ; mère-fille ~1,25% ; vérification contre documents sources.",
    chips:[
      {lbl:"Valeur du groupe", q:"Combien vaut Orion Capital et comment se décompose la NAV ?"},
      {lbl:"Top 3 risques", q:"Quels sont les 3 principaux risques de ce portefeuille de démonstration ?"},
      {lbl:"Cash-flow 2035", q:"Quel sera le cash-flow quote-part en 2035 ?"},
      {lbl:"Prêts < 2032", q:"Quels prêts s'éteignent avant 2032 ?"},
      {lbl:"Meilleur rendement", q:"Quel actif a le meilleur rendement et le meilleur couple rendement/risque ?"},
      {lbl:"Distribution 200k€", q:"Quel est l'impact d'une distribution de 200 k€ vers Orion Capital et la voie la plus efficace ?"}
    ]
  },
  docExpected:[
  ["Comptes annuels 2025",["bilan","plaquette","comptes annuels","ex_client","ex banques","ex_bqe"],"Plaquette / bilan + compte de résultat au 31/12/2025"],
  ["Liasse fiscale 2025",["2572","liasse","liquidation is"],"Imprimé 2572 (liquidation IS) de l'exercice"],
  ["Bail commercial",["bail","aae","acte","locataire","lease"],"Bail signé + avenants + identité locataire"],
  ["Tableaux d'emprunt",["emprunt","prêt","pret","modulimmo","crd","tableau d'amort"],"Tableau d'amortissement à jour de chaque prêt"],
  ["Vie sociale (statuts/AG)",["statut","pacte","ago","agoa","pv","convocation","cession"],"Statuts, pacte d'associés, derniers PV d'AG"],
  ["Valorisation",["expertise","galtier","teaser","valeur vénale","avis de valeur"],"Expertise ou avis de valeur récent du bien"]
  ],
  buildings:{
  vega:{c:"#FFC861",addr:"ZI des Lumières, ville fictive A — entrepôt + bureaux",reno:"Bail Helios Énergie (effet 2026, fictif)",
    parts:[{k:"acti",lbl:"Activité / entrepôt",s:3600},{k:"bureaux",lbl:"Bureaux",s:800},{k:"terrain",lbl:"Terrain",s:12500}]},
  altair:{c:"#6FE3FF",addr:"Parc Altaïr, ville fictive B — R+1",reno:"Lumitech Industries (bail ~2032, fictif)",
    parts:[{k:"acti",lbl:"Surface activité",s:1200},{k:"bureaux",lbl:"Bureaux",s:0},{k:"terrain",lbl:"Terrain",s:0}]},
  lyra:{c:"#FF6B5A",addr:"Rue des Forges, ville fictive C",reno:"Translog Massif (bail fin 2026, fictif)",
    parts:[{k:"acti",lbl:"Activité",s:1900},{k:"bureaux",lbl:"Bureaux",s:420},{k:"archives",lbl:"Archives",s:180},{k:"hangar",lbl:"Hangar",s:450},{k:"terrain",lbl:"Terrain clos",s:8200}]},
  cygnus:{c:"#A78BFF",addr:"ZA des Vignes, ville fictive D",reno:"Bac acier — Batinova TP (fictif)",
    parts:[{k:"acti",lbl:"Industriel",s:1500},{k:"terrain",lbl:"Terrain enrobé clos",s:15000}]},
  polaris:{c:"#FF8FD6",addr:"5 place du Zénith, ville fictive E",reno:"Bureaux de centre-ville — siège Nova Conseil (fictif)",
    parts:[{k:"bureaux",lbl:"Bureaux",s:95}]},
  delta:{c:"#FFE08A",addr:"21 avenue des Astres, ville fictive F",reno:"2 studios + T3 (résidence gérée fictive)",parts:[]}
  },
  entities:[
   {id:"advisory", name:"NOVA CONSEIL", type:"Exploitation — conseil immobilier", stake:0.50, color:"#5CE6A1", tex:"emerald",
    arch:"aurora",
    surf:{w:24,d:18,h:12, col:0x1E242C, band:0x3AE8A0, sign:"NOVA CONSEIL",   anim:"flag",  vcol:0x3AE8A0},
    lat:45.5250, lng:4.8740, addr:"12 quai des Étoiles (adresse fictive)",
    marketValue:0, cash:315000, finAssets:0, ccHP:0, ccTotal:0, rent:0, result:0,
    loans:[], tenant:"50/50 avec un partenaire fictif — PDS 5 500€ HT/mois chacun",
    leaseEnd:null, risk:"warn",
    history:{years:[2024,2025,2026],cash:[190000,262000,315000]},
    events:[{y:2026,t:"cash",txt:"Pic de trésorerie (fictif) : 315 000€"},{y:2028,t:"risk",txt:"⚠️ Tréso sous tension sans nouveaux mandats (scénario démo)"},{y:2026,t:"deal",txt:"Honoraires Vega ~260k€ HT encaissés (fictif)"}],
    docs:["Prévisionnel trésorerie Nova Conseil 2026-2029 (fictif)"],
    notes:"Société d'exploitation fictive. Pic de trésorerie 2026 : 315 000€. Sans nouveaux mandats après 2026 : tension de trésorerie dès 2028 (scénario de démonstration). Valorisation prudente = quote-part de trésorerie uniquement."},

   {id:"vega", name:"EP VEGA", type:"Société immobilière (IS)", stake:0.25, color:"#FFC861", tex:"gold",
    arch:"banded", fx:["saturnRings"], rentRamp:{y:2026, k:0.25},
    surf:{w:46,d:20,h:11, col:0xB8BEC6, band:0xE8632A, sign:"EP VEGA",        anim:"crane", vcol:0xE8632A},
    lat:45.5860, lng:5.2730, addr:"ZI des Lumières (fictif) — 3 600 m² bâti / 12 500 m²",
    marketValue:5400000, cash:0, finAssets:0, ccHP:85000, ccTotal:420000, rent:486000, result:0,
    loans:[{label:"Prêt A (banque fictive)", crd:2100000, rate:3.40, amortYear:118000, end:2041},
           {label:"Prêt B (banque fictive)", crd:2100000, rate:3.40, amortYear:118000, end:2041}],
    tenant:"Helios Énergie (groupe fictif)", leaseEnd:2039, risk:"ok",
    history:{years:[2026],debt:[4200000]},
    events:[{y:2026,t:"deal",txt:"Acquisition + travaux (scénario fictif)"},{y:2026,t:"lease",txt:"Prise d'effet bail Helios Énergie (fictif)"},{y:2036,t:"risk",txt:"Deadline avenant pacte d'associés (fictif)"},{y:2039,t:"lease",txt:"Fin ferme bail Helios (fictif)"},{y:2041,t:"loan",txt:"Extinction prêts A+B (4,2M€ fictifs)"}],
    docs:["Bail notarié Helios (fictif)","Avis de valeur 5 400 000€ (fictif)","BP & prévisionnel tréso (fictif)","Pacte d'associés (fictif)"],
    notes:"Actif logistique fictif. Loyer 486 000€/an indexé ILAT, franchise 6 mois. Service dette ~427k€/an, DSCR ~1,14. Excédent annuel de démonstration ~55-70k€. Tous les montants sont inventés."},

   {id:"altair", name:"EP ALTAIR", type:"SAS à l'IS", stake:0.40, color:"#6FE3FF", tex:"ice",
    fx:["polarCaps"], capLat:0.55,
    surf:{w:34,d:16,h:9,  col:0xEAEDF2, band:0x1E6FD8, sign:"LUMITECH",       anim:"smoke", vcol:0x1E6FD8},
    lat:45.0460, lng:5.0520, addr:"Parc Altaïr (fictif) — 1 200 m² R+1",
    marketValue:2150000, cash:240000, finAssets:0, ccHP:22000, ccTotal:150000, rent:182000, result:51000,
    loans:[{label:"Emprunt bancaire fictif 1 500 k€", crd:905000, rate:1.90, amortYear:92000, end:2034}],
    tenant:"Lumitech Industries (groupe fictif)", leaseEnd:2032, risk:"ok",
    history:{years:[2019,2020,2021,2022,2023,2024,2025],
      ca:[74000,151000,158000,163000,169000,175000,182000],
      rn:[-51000,21000,29000,33000,38000,44000,51000],
      cp:[-46000,-22000,9000,44000,84000,131000,184000],
      debt:[1440000,1352000,1263000,1174000,1085000,995000,905000]},
    events:[{y:2026,t:"cash",txt:"Scénario B : remboursement partiel CC (OC +15 000€, fictif)"},{y:2029,t:"cash",txt:"Échéance placement 60k€ (fictif)"},{y:2032,t:"lease",txt:"Échéance bail Lumitech (fictif)"},{y:2034,t:"loan",txt:"Extinction emprunt (fictif)"}],
    docs:["Rapport gestion + PV AGO 2026 (fictif)","Liasse 2025 (fictive)","Série bilans 2019→2025 (fictive)"],
    notes:"Société fictive de démonstration. 2025 : CA 182 000€, RN 51 000€, CP 184 000€ — bénéfice affecté en réserves, aucun dividende. Liquidités 240 000€. CC non rémunérés répartis entre associés fictifs. 7 exercices de redressement illustratifs."},

   {id:"lyra", name:"EP LYRA", type:"SAS à l'IS (ex-SARL)", stake:0.30, color:"#FF6B5A", tex:"mars",
    surf:{w:40,d:18,h:10, col:0xCFD6DD, band:0xC8321E, sign:"EP LYRA",        anim:"trucks",vcol:0xC8321E},
    lat:45.4400, lng:4.3900, addr:"8 rue des Forges (fictif) — 1 900 m² + annexes / 8 200 m²",
    marketValue:1850000, cash:205000, finAssets:0, ccHP:40000, ccTotal:310000, rent:201000, result:44000,
    loans:[{label:"Emprunt bancaire fictif", crd:1120000, rate:1.60, amortYear:101000, end:2037}],
    tenant:"Translog Massif (groupe fictif)", leaseEnd:2027, risk:"risk",
    history:{years:[2022,2023,2024,2025], rn:[36000,38500,41800,44000],
      debt:[1420000,1320000,1221000,1120000], cash:[120000,148000,176000,205000]},
    events:[{y:2026,t:"risk",txt:"⚠️ Fin bail ferme fin 2026 (fictif)"},{y:2027,t:"risk",txt:"⚠️ Échéance mi-2027 : relocation / arbitrage / portage (démo)"},{y:2037,t:"loan",txt:"Extinction emprunt (fictif)"}],
    docs:["Rapport gestion + PV AGO 2026 (fictif)","Liasse 2025 (fictive)","Bail Translog + caution (fictifs)"],
    notes:"⚠️ RISQUE N°1 (scénario fictif) : bail ferme fin 2026, prolongé mi-2027 — recherche locataire en cours. Trésorerie à vacance ~205k€ ≈ 18 mois de charges à vide (~11,5k€/mois). 2025 : CA 201 000€, RN 44 000€. Tous les chiffres sont inventés."},

   {id:"cygnus", name:"SCI CYGNUS", type:"SCI", stake:0.10, color:"#A78BFF", tex:"violet",
    arch:"cratered", fx:["thinRing"], ccRate:3.90, ccNote:"Perte du seul CC rémunéré (3,90%, fictif) au prorata.",
    surf:{w:30,d:14,h:8,  col:0xC9CFD8, band:0x2A5CA8, sign:"CYGNUS",         anim:"yard",  vcol:0x2A5CA8},
    lat:46.3000, lng:4.8300, addr:"ZA des Vignes (fictif) — 1 500 m² + 1,5 ha clos",
    marketValue:1200000, cash:96000, finAssets:0, ccHP:15000, ccTotal:280000, rent:118000, result:31000,
    loans:[{label:"Prêt bancaire fictif 1,1 M€ (1,35%)", crd:402000, rate:1.35, amortYear:76000, end:2032}],
    tenant:"Batinova TP (groupe fictif)", leaseEnd:2035, risk:"ok",
    history:{years:[2024,2025], ca:[112000,118000], rn:[26500,31000], debt:[478000,402000]},
    events:[{y:2032,t:"loan",txt:"Extinction prêt (fictif)"},{y:2035,t:"lease",txt:"Fin bail 12 ans fermes (fictif)"}],
    docs:["Plaquette 2025 (fictive)","AGO 2026 (fictive)","Grand livre CC 2025 (fictif)"],
    notes:"SCI fictive. CC OC 15 000€ rémunéré 3,90% (~585€/an — seul CC rémunéré de la démo). 2025 : CA 118 000€, RN 31 000€. Bâtiment industriel fictif, 1,5 ha enrobés clos."},

   {id:"polaris", name:"SCI POLARIS", type:"SCI à l'IS", stake:0.50, color:"#FF8FD6", tex:"rose",
    arch:"city",
    surf:{w:16,d:14,h:20, col:0xE9DFC8, band:0x8A8F98, sign:"POLARIS",        anim:"win",   vcol:0xFF5AC8},
    lat:45.9900, lng:4.7200, addr:"5 place du Zénith (adresse fictive)",
    marketValue:520000, cash:62000, finAssets:0, ccHP:48000, ccTotal:96000, rent:41000, result:8200,
    loans:[{label:"Emprunt bancaire fictif", crd:296000, rate:1.80, amortYear:21000, end:2039}],
    tenant:"Locatif centre-ville fictif — co-gérance 50/50", leaseEnd:null, risk:"warn",
    history:{years:[2024,2025], rn:[7100,8200], cp:[-24000,-15800], debt:[317000,296000]},
    events:[{y:2029,t:"cash",txt:"RAN négatif résorbé (estimation démo) → dividendes possibles"},{y:2039,t:"loan",txt:"Extinction emprunt (fictif)"}],
    docs:["Plaquette 31/12/2025 (fictive)","PV AGOA 2026 (fictif)"],
    notes:"SCI fictive. CP -15 800€ au 31/12/2025 (en amélioration ~+8k/an). RN 2025 +8 200€ affecté en RAN. Pas de dividende tant que RAN négatif. Tous les montants sont inventés."},

   {id:"nova", name:"NOVA HOLDING", type:"Holding", stake:0.50, color:"#5CC8FF", tex:"azure",
    arch:"ice",
    surf:{w:14,d:14,h:24, col:0x24303E, band:0x58C8FF, sign:"NOVA HOLDING",   anim:"win",   vcol:0x58C8FF},
    lat:45.8950, lng:4.4350, addr:"3 rue des Comètes (adresse fictive)",
    marketValue:0, cash:4200, finAssets:152000, ccHP:9500, ccTotal:41000, rent:0, result:700,
    loans:[], tenant:"Holding fictive 50/50 Orion Capital + partenaire fictif", leaseEnd:null, risk:"ok",
    history:{years:[2024,2025], rn:[-150,700]},
    events:[{y:2026,t:"cash",txt:"💰 Remontée liquidation fictive : ~240k€ (part OC ~120k€)"}],
    docs:["Plaquette + bilan 2025 (fictifs)","Cession de parts (fictive)","Détail comptes courants (fictif)"],
    notes:"Holding fictive détenant ~9% d'une participation en liquidation (scénario démo) → encaisse ~240k€ d'ici fin 2026. Part effective OC ≈ 50% (~120k€) + CC 9 500€. Montant exact via décompte de liquidation (fictif)."},

   {id:"delta", name:"DELTA (DIRECT)", type:"Détention directe Orion Capital", stake:1.0, color:"#FFE08A", tex:"sand",
    arch:"ocean",
    surf:{w:18,d:12,h:17, col:0xD8CDBD, band:0x6E7B8A, sign:"DELTA",          anim:"win",   vcol:0xFFB050},
    lat:44.9330, lng:4.8920, addr:"21 avenue des Astres (fictif) — 2 studios + 1 T3",
    marketValue:480000, cash:0, finAssets:0, ccHP:0, ccTotal:0, rent:24600, result:-2100,
    loans:[{label:"2 prêts amortissables fictifs", crd:315000, rate:3.20, amortYear:17500, end:2042}],
    tenant:"Résidence gérée fictive (10 200€/an) + T3 meublé (14 400€/an)", leaseEnd:null, risk:"warn",
    history:{years:[2025], debt:[315000]},
    events:[{y:2042,t:"loan",txt:"Extinction prêts (fictif)"}],
    docs:["Contrats de prêt (fictifs)","Baux résidence + meublé (fictifs)"],
    notes:"Détention directe fictive. Loyers 24 600€/an, service dette ~27 580€/an, TF+copro ~2 600€ → CF ≈ -2 100€/an avant IS. Zéro vacance (scénario démo)."}
  ],
  globalEvents:[
   {y:2026,t:"deal",txt:"Vega : acquisition + bail Helios Énergie (fictif)"},
   {y:2026,t:"cash",txt:"Nova : remontée liquidation ~120k€ (part OC, fictif)"},
   {y:2026,t:"deal",txt:"Direction financière — IS OC optimisé (démo)"},
   {y:2027,t:"risk",txt:"Lyra : décision avant l'été (fictif)"},
   {y:2027,t:"risk",txt:"Nova Conseil : nouveaux mandats indispensables (démo)"},
   {y:2029,t:"cash",txt:"Altair : échéance placement 60k€ (fictif)"},
   {y:2032,t:"lease",txt:"Lumitech : échéance bail (fictif)"},
   {y:2032,t:"loan",txt:"Cygnus : extinction prêt (fictif)"},
   {y:2034,t:"loan",txt:"Altair : extinction emprunt (fictif)"},
   {y:2035,t:"lease",txt:"Cygnus : fin bail Batinova (fictif)"},
   {y:2036,t:"risk",txt:"Vega : deadline avenant pacte (fictif)"},
   {y:2037,t:"loan",txt:"Lyra : extinction emprunt (fictif)"},
   {y:2039,t:"lease",txt:"Helios : fin ferme du bail (fictif)"},
   {y:2041,t:"loan",txt:"Vega 4,2M€ + Polaris + Delta : extinctions (fictif)"},
   {y:2041,t:"lease",txt:"Helios : fin totale — patrimoine désendetté (démo)"}
  ],
  glossaryCtx:{
   "patrimoine brut qp":"Dans cette démo ≈ 3,1 M€ en quote-part, pour ~11,8 M€ à 100 % des véhicules. L'écart entre brut et NAV, c'est l'effet de la dette et l'effet de levier.",
   "dette":"Plus la dette est élevée face à la valeur, plus le levier — et le risque — sont forts. On la suit véhicule par véhicule via la LTV.",
   "valeur venale":"Pour EP Vega (fictif), l'avis de valeur retient 5 400 k€. C'est la base de calcul de la LTV et de la quote-part d'ANR.",
   "dette crd":"C'est le chiffre qui compte pour la LTV et pour estimer ce que rapporterait une revente après remboursement de la banque.",
   "loyer an":"Pour EP Vega (fictif), 486 k€/an. C'est le moteur du rendement et de la capacité à rembourser la dette.",
   "rendement":"EP Vega ≈ 9 % (486 k€ ÷ 5 400 k€, chiffres fictifs) : soutenu pour de l'activité. Un rendement « prime » de bureaux tournerait plutôt autour de 5-7 %.",
   "cash flow":"EP Vega (fictif) ressort à ≈ +59 k€ : le loyer couvre la dette. À l'inverse, Delta est légèrement négatif.",
   "qp nav cc":"C'est la « contribution » de chaque planète à la NAV totale d'Orion Capital (démo). Le CC est récupérable sans frottement fiscal, contrairement au dividende.",
   "qp cc":"Indicateur de ce que « pèse » réellement la ligne dans le patrimoine de démonstration, dette déduite.",
   "quote part":"Ex. 25 % sur EP Vega, 50 % sur Nova Conseil, 100 % sur Delta (chiffres fictifs). C'est le coefficient qui pondère tous les montants « en quote-part ».",
   "ltv":"EP Vega est à ≈ 78 % au départ (chiffres fictifs) : levier optimisé, à surveiller tant que la dette n'a pas baissé.",
   "tresorerie placements":"Sert à absorber une vacance locative ou un imprévu. Pour Lyra (fictif), ce coussin finance ~18 mois de vacance possible.",
   "resultat net":"Quand le résultat net devient durablement positif et que les reports déficitaires sont épuisés, l'IS « plein » réapparaît (cas de Lyra dans la démo).",
   "is":"L'IS permet d'amortir le bâtiment (donc de réduire l'impôt), mais une revente peut déclencher une plus-value taxée plus lourdement qu'à l'IR.",
   "surloyer":"Dans la démo, un complément de loyer sur EP Vega dope le rendement de départ (illustration).",
   "ilat":"Plusieurs baux du portefeuille démo sont indexés ILAT — d'où la hausse mécanique des loyers projetés.",
   "valeur retenue":"En cliquant « Appliquer à la NAV », elle devient la valeur vénale du véhicule et recalcule tout le patrimoine (démo).",
   "prix au m2":"Ex. 1 900 m2 d'activité à 800 €/m2 = 1 520 000 € (fictif). La somme des composantes donne la valeur du bâtiment.",
   "surface activite":"Lyra (fictif) : 1 900 m2 d'activité ; Vega : 3 600 m2 d'entrepôt.",
   "surface bureaux":"Lyra (fictif) : 420 m2 de bureaux en plus de l'activité.",
   "terrain":"Vega : 12 500 m2 de terrain ; Cygnus : ~15 000 m2 enrobés et clôturés (fictifs).",
   "patrimoine immobilier estime":"Cet onglet l'actualise en direct à mesure que tu saisis les prix.",
   "service de la dette":"Si le loyer couvre largement le service de la dette, le bien dégage du cash-flow positif.",
   "amortissement":"L'atout des sociétés à l'IS : il abaisse l'impôt durant des années, mais réduit la valeur nette comptable.",
   "report deficitaire":"Quand le stock est épuisé, l'IS « plein » réapparaît (cas de Lyra dans la démo).",
   "pfu":"D'où l'intérêt de récupérer un compte courant (neutre) plutôt qu'un dividende taxé à 30 %.",
   "dividende":"Moins efficient que le remboursement de compte courant : ~30 % partent en impôt.",
   "vacance locative":"Lyra (fictif) : ~205 k€ de tréso ≈ 18 mois de charges à vide en cas de départ du locataire.",
   "expertise":"Pour Vega (fictif), l'avis de valeur retient 5 400 k€.",
   "acte en mains":"Sur Vega (fictif), ≈ 8,4 % acte en mains : frais intégrés, d'où un chiffre un peu inférieur au rendement brut.",
   "bail ferme":"EP Vega (fictif) : 12 ans fermes (fin ferme 2039). Plus la fermeté est longue, plus la valeur et le financement sont solides.",
   "nav-brand":"Dans cette démo ≈ 1,1 M€. C'est l'indicateur de tête : il agrège la quote-part d'ANR de chaque véhicule, les comptes courants détenus, et la trésorerie au niveau holding.",
   "cc-brand":"Levier de liquidité clé : récupérer un CC est neutre fiscalement, contrairement à un dividende taxé au PFU (~30 %)."
  }
};
